# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Welcome test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  file_io:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Check file_io.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Try file_io.py 
      run: python file_io.py
      
  comprehensions:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Check comprehensions.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Try comprehensions.py 
      run: python comprehensions.py
  
  numpy2d:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Check numpy2d.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
    - name: Try numpy2d.py 
      run: python numpy2d.py
      
  modules:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Check modules.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Try modules.py 
      run: python modules.py
